# Site settings
title: Private Machine Learning
header-img: img/home-bg.jpg
#copyright_name: Your/Project/Corporate Name
description: "Mixing modern cryptography and machine learning in a quest for private machine learning"
baseurl: ""
url: "https://mortendahl.github.io"
twitter_username: mortendahlcs
github_username: mortendahl

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json"]

gems: [jekyll-paginate, jekyll-feed]