# Site settings
title: Cryptography and Machine Learning
header-img: img/home-bg.jpg
#copyright_name: Your/Project/Corporate Name
description: "Mixing both for private data analysis"
baseurl: ""
url: "https://mortendahl.github.io"
twitter: mortendahlcs
github: mortendahl

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json"]

gems: [jekyll-paginate, jekyll-feed]